services:
  video-image-tool:
    image: milodk/video-image-tool-v4:latest
    build: .
    # image: milodk/video-image-tool-v4:latest
    container_name: video-image-tool-v4
    ports:
      - "7863:7860"
    volumes:
      - ./output:/app/output
      - ./sessions:/app/sessions
    environment:
      - OUTPUT_DIR=/app/output
      - SESSIONS_DIR=/app/sessions
      - DEFAULT_BASE_URL=https://moai.wiki
      - DEFAULT_MODEL=gemini-3.1-flash-image-preview-2k
      - GEMINI_RESPONSE_MODALITIES=TEXT,IMAGE
      - ENABLE_IMAGE_TIMEOUT_FALLBACK=false
      - DEFAULT_VIDEO_BASE_URL=https://moai.wiki
      - DEFAULT_VIDEO_MODEL=grok-imagine-1.0-video
      - DEFAULT_GPT_IMAGE_BASE_URL=https://moai.wiki
      - DEFAULT_GPT_IMAGE_MODEL=gpt-image-2-flatfee
      - DEFAULT_REQUEST_TIMEOUT=60
    restart: unless-stopped
